name: Deploy🪽

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      secrets_txt:
        description: "Paste secrets here (format: KEY=VALUE)"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.7

      - name: Import secrets
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ] && [ -n "${{ inputs.secrets_txt }}" ]; then
            echo "${{ inputs.secrets_txt }}" > secrets.txt
          elif [ -f .env.example ]; then
            cp .env.example secrets.txt
          fi
          
          if [ -f secrets.txt ]; then
            while IFS='=' read -r key value; do
              if [[ -n "$key" && -n "$value" && ! "$key" =~ ^# ]]; then
                echo "$key=$value" >> $GITHUB_ENV
              fi
            done < secrets.txt
          fi

      - name: Node.js setup
        uses: actions/setup-node@v4.0.2

      - name: Dependencies install
        run: |
          if [ -f yarn.lock ]; then
            yarn install
          else
            npm install
          fi

      - name: Detect framework & build
        run: |
          if [ -f vite.config.ts ] || [ -f vite.config.js ]; then
            echo "Detected Vite project"
            yarn run build || npm run build
            echo "VITE_PROJECT=true" >> $GITHUB_ENV
          elif [ -f next.config.js ] || [ -f next.config.ts ]; then
            echo "Detected Next.js project"
            yarn run build || npm run build
            touch ./out/.nojekyll
            echo "NEXT_PROJECT=true" >> $GITHUB_ENV
          else
            echo "Unsupported framework!" && exit 1
          fi

      - name: Upload build artifacts (for Vite)
        if: env.VITE_PROJECT == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Upload build artifacts (for Vite)
        if: env.VITE_PROJECT == 'true'
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: Deploy GitHub Pages (Vite)
        if: env.VITE_PROJECT == 'true'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

      - name: Deploy GitHub Pages (Next.js)
        if: env.NEXT_PROJECT == 'true'
        uses: JamesIves/github-pages-deploy-action@v4.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: public
          folder: out