name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      secrets_txt:
        description: "Paste secrets here (format: KEY=VALUE)"
        required: false

jobs:
  build:
    name: Build file 🔨
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Import secrets
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ] && [ -n "${{ inputs.secrets_txt }}" ]; then
            echo "${{ inputs.secrets_txt }}" > secrets.txt
          elif [ -f .env.example ]; then
            cp .env.example secrets.txt
          fi
          
          if [ -f secrets.txt ]; then
            while IFS='=' read -r key value; do
              if [[ -n "$key" && -n "$value" && ! "$key" =~ ^# ]]; then
                echo "$key=$value" >> $GITHUB_ENV
              fi
            done < secrets.txt
          fi

      - name: Node setup
        uses: actions/setup-node@v3

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Repository name
        run: echo "VITE_BASE_PATH=/$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)" >> $GITHUB_ENV

      - name: Build project
        run: npm run build

      - name: Production files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy 🚀
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ env.DEPLOY_URL }}

    steps:
      - name: Artifacts upload
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: Check for CNAME
          run: |
            if [ -f ./dist/CNAME ]; then
              echo "DEPLOY_URL=https://$(cat ./dist/CNAME)" >> $GITHUB_ENV
            else
              echo "DEPLOY_URL=https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/" >> $GITHUB_ENV
            fi

      - name: Deploy gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: production