name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build file 🔨
    runs-on: ubuntu-latest

    steps:
      - name: Kiểm tra repo 🛎️
        uses: actions/checkout@v3

      - name: Check required app secrets from .env.example
        run: |
          # Parse .env.example and collect variable names
          required_secrets=()
          while IFS= read -r line; do
            # Skip comments, empty lines, and lines without '='
            if [[ -z "$line" || "$line" =~ ^\# || "$line" != *"="* ]]; then
              continue
            fi
            # Extract variable name (assuming format VAR=VALUE)
            if [[ "$line" =~ ^[[:space:]]*([[:alnum:]_]+)= ]]; then
              required_secrets+=("${BASH_REMATCH[1]}")
            fi
          done < .env.example

          # Remove duplicate entries and log required secrets
          readarray -t unique_secrets < <(printf '%s\n' "${required_secrets[@]}" | awk '!seen[$0]++')
          echo "Required secrets from .env.example: ${unique_secrets[*]}"

          # Check for missing secrets
          missing=()
          for secret in "${unique_secrets[@]}"; do
            # Replace null/empty values with empty string for check
            [[ -n "${!secret+x}" ]] || missing+=("$secret")
          done

          if [ ${#missing[@]} -gt 0 ]; then
            echo "ERROR: Missing required secrets from .env.example: ${missing[*]}"
            exit 1
          else
            echo "All required secrets are present."
          fi

      - name: Cài node 📦
        uses: actions/setup-node@v3

      - name: Cài dependencies 🪛
        uses: bahmutov/npm-install@v1

      - name: 🔍 Tìm tên repository
        run: echo "VITE_BASE_PATH=/$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)" >> $GITHUB_ENV

      - name: Build dự án 🏗️
        run: npm run build

      - name: Đẩy lên production 📂
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy 🚀
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Tải artifact 🐈‍⬛
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: Deploy lên nhánh gh-pages 🌐
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
