name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build file 🔨
    runs-on: ubuntu-latest

    steps:
      - name: Kiểm tra repo 🛎️
        uses: actions/checkout@v3

      - name: Cài node 📦
        uses: actions/setup-node@v3

      - name: Cài dependencies 🪛
        uses: bahmutov/npm-install@v1

      - name: Build dự án 🏗️
        run: npm run build

      - name: Đẩy lên production 📂
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy 🚀
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Tải artifact 🐈‍⬛
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist

      - name: Deploy lên nhánh gh-pages 🌐
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist