name: Deploy

on:
  push:
    branches:
      - main # 🔄 Mỗi lần push lên main, workflow sẽ chạy
  workflow_dispatch:
    inputs:
      secrets_txt:
        description: "Paste secrets here (format: KEY=VALUE)"
        required: false

jobs:
  build:
    name: Build file 🔨
    runs-on: ubuntu-latest

    steps:
      - name: Kiểm tra repo 🛎️
        uses: actions/checkout@v3

      - name: Đọc secrets từ input hoặc .env.example
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ] && [ -n "${{ inputs.secrets_txt }}" ]; then
            echo "${{ inputs.secrets_txt }}" > secrets.txt
          elif [ -f .env.example ]; then
            cp .env.example secrets.txt
          fi
          
          if [ -f secrets.txt ]; then
            while IFS='=' read -r key value; do
              if [[ -n "$key" && -n "$value" && ! "$key" =~ ^# ]]; then
                echo "$key=$value" >> $GITHUB_ENV
              fi
            done < secrets.txt
          fi

      - name: Check secrets 🔑
        run: |
          echo "Available Secrets:"
          env | grep -E '^[A-Z0-9_]+=' | cut -d= -f1 | sort

      - name: Cài node 📦
        uses: actions/setup-node@v3

      - name: Cài dependencies 🪛
        uses: bahmutov/npm-install@v1

      - name: 🔍 Tìm tên repository
        run: echo "VITE_BASE_PATH=/$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)" >> $GITHUB_ENV

      - name: Build dự án 🏗️
        run: npm run build

      - name: Đẩy lên production 📂
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy 🚀
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Tải artifact 🐈‍⬛
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: Deploy lên nhánh gh-pages 🌐
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist